on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
name: Build

jobs:
  flatpak:
    permissions:
      contents: write
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: gotraceui.flatpak
        manifest-path: co.honnef.Gotraceui.json
        branch: stable
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: gotraceui.flatpak
